"""Which forward values a graph pair retains for its backward, and why.

AOTAutograd traces a stage into one joint graph and then splits it: the
values the backward is handed are the forward's saved outputs, and the rest
of what the backward needs it computes again. Where that split falls is the
difference between the two variants a stage offers. The ``recompute``
variant retains only the stage's inputs. The ``save`` variant retains what
would be expensive to rebuild and regenerates the rest, and this module is
the rule that says which is which.

The rule is arithmetic intensity. Below a device's ridge point an operator's
runtime is set by the bytes it moves, not by its flops, so regenerating its
result costs one pass over its bytes however many flops it does: a
normalization, an activation, a rotation, a cast, a gather. Above the ridge
the cost per regenerated byte grows with the flops without bound: a matrix
product, an attention, a convolution. The threshold sits well under any ridge
point in use, so the classification does not depend on the machine and a
poor kernel near the boundary still costs about one pass.

Flops come from PyTorch's flop counter, which knows every ATen matrix
product, convolution and attention, and any custom operator whose library
registered a formula; bytes come from the traced geometry. An ATen or prims
operator without a formula is memory-bound, which is PyTorch's own stance in
its denylist. A custom operator without a formula is unknown, and unknown is
treated as compute-bound: a library that declares nothing has its values
saved, as they always were, and never regenerated on a guess.

The min-cut solver decides the rest. A regenerated value's inputs have to be
retained instead, and the solver charges for them, so a value is regenerated
only when the bytes it saves exceed the bytes its regeneration keeps: a
normalization's output goes because its input is kept for the
normalization's own backward; a rotation's output stays because its input is
the same size and is kept for nothing else.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

import torch
from torch._functorch import config as functorch_config
from torch._functorch.partitioners import min_cut_rematerialization_partition
from torch.fx.node import map_arg
from torch.utils._pytree import tree_flatten
from torch.utils.checkpoint import CheckpointPolicy
from torch.utils.flop_counter import FlopCounterMode, flop_registry

from shadowspill.errors import CaptureError

from .effects import join_recomputed_effects

#: Flops per byte moved, at or below which an operator is memory-bound and the
#: ``save`` variant regenerates its results rather than retaining them.
MEMORY_BOUND_FLOPS_PER_BYTE = 16.0

#: The namespaces whose operators are PyTorch's own.
_BUILTIN_NAMESPACES = frozenset({"aten", "prims"})

#: The partitioner bans that encode "recompute is free only when the compiler
#: fuses it", which is the premise the intensity rule replaces, and the one
#: that would make a parameter free to keep when a plan pays a fetch for it.
_LIFTED_BANS: Mapping[str, Any] = {
    "ban_recompute_not_in_allowlist": False,
    "ban_recompute_materialized_backward": False,
    "ban_recompute_used_far_apart": False,
    "ban_recompute_long_fusible_chains": False,
    "treat_parameters_as_free_to_save": False,
}


class OperatorClass(StrEnum):
    """What regenerating one operator's results costs."""

    #: One pass over its bytes: it may be regenerated.
    MEMORY_BOUND = "memory_bound"
    #: More than that, growing with its flops: it is retained.
    COMPUTE_BOUND = "compute_bound"
    #: A custom operator with no flop formula: retained, as if compute-bound.
    UNKNOWN = "unknown"


@dataclass(frozen=True, slots=True)
class RetentionPolicy:
    """What the ``save`` variant may regenerate: everything memory-bound."""

    memory_bound_flops_per_byte: float = MEMORY_BOUND_FLOPS_PER_BYTE

    def __post_init__(self) -> None:
        value = self.memory_bound_flops_per_byte
        if isinstance(value, bool) or not isinstance(value, int | float):
            raise TypeError("memory_bound_flops_per_byte must be a number")
        if not math.isfinite(value) or value < 0:
            raise ValueError(
                "memory_bound_flops_per_byte must be finite and non-negative"
            )
        object.__setattr__(self, "memory_bound_flops_per_byte", float(value))

    def identity(self) -> dict[str, object]:
        return {"memory_bound_flops_per_byte": self.memory_bound_flops_per_byte}

    def classify(self, node: torch.fx.Node) -> OperatorClass | None:
        """Classify one traced operator, or ``None`` for a node that is not one."""

        return _classify(node, self.memory_bound_flops_per_byte)

    def operator_classes(self, graph_module: torch.fx.GraphModule) -> dict[str, str]:
        """How this policy classes every custom operator in ``graph_module``.

        PyTorch's own operators class the same way under one PyTorch build,
        which a graph's structural contract already names. A custom
        operator's class moves when its library registers or corrects a
        formula, so a store keyed by this dictionary misses when the answer
        would change rather than reading back a pair built under the old one.
        """

        classes: dict[str, str] = {}
        for node in graph_module.graph.nodes:
            if node.op != "call_function" or _is_builtin(node.target):
                continue
            operator_class = self.classify(node)
            if operator_class is not None:
                classes[str(node.target)] = operator_class.value
        return dict(sorted(classes.items()))

    def digest(self, graph_module: torch.fx.GraphModule) -> str:
        """One digest of the policy and the classes it gives a graph's operators."""

        encoded = json.dumps(
            {**self.identity(), "operators": self.operator_classes(graph_module)},
            sort_keys=True,
            separators=(",", ":"),
        )
        return hashlib.sha256(encoded.encode()).hexdigest()


@dataclass(frozen=True, slots=True)
class RetentionSummary:
    """What one partition regenerated, under which policy."""

    memory_bound_flops_per_byte: float
    #: Forward operators the backward computes again rather than being handed.
    regenerated_operators: tuple[str, ...] = ()
    #: Custom operators no formula prices, retained as if compute-bound.
    unknown_operators: tuple[str, ...] = ()

    def identity(self) -> dict[str, object]:
        return {
            "memory_bound_flops_per_byte": self.memory_bound_flops_per_byte,
            "regenerated_operators": list(self.regenerated_operators),
            "unknown_operators": list(self.unknown_operators),
        }


@dataclass(slots=True)
class RetentionRecord:
    """Where a partition callback leaves its summary for the caller."""

    summary: RetentionSummary | None = field(default=None)

    def require(self) -> RetentionSummary:
        if self.summary is None:
            raise RuntimeError("AOTAutograd did not partition the graph pair")
        return self.summary


def partition_function(
    memory_budget: float,
    policy: RetentionPolicy,
    record: RetentionRecord,
) -> Callable[..., tuple[torch.fx.GraphModule, torch.fx.GraphModule]]:
    """The AOT partition callback for one variant.

    ``aot_function`` partitions on its first invocation, after the caller's
    construction scope has returned, so the budget and the bans are bound
    inside the callback rather than around the construction; wrapping the
    construction would silently observe the ambient Functorch configuration
    instead.

    Budget ``1.0`` is the ``save`` variant: min-cut over saved bytes with
    compute-bound and unknown operators marked as values to save and every
    memory-bound one free to regenerate. Budget ``0.0`` is ``recompute``,
    which retains the inputs alone and reads no mark. A budget between the
    two is PyTorch's knapsack over the same marks.
    """

    def partition(
        joint_module: torch.fx.GraphModule,
        joint_inputs: object,
        **kwargs: Any,
    ) -> tuple[torch.fx.GraphModule, torch.fx.GraphModule]:
        marked, unknown = _mark_retained(joint_module, policy)
        with functorch_config.patch(
            activation_memory_budget=memory_budget, **_LIFTED_BANS
        ):
            forward, backward = min_cut_rematerialization_partition(
                joint_module, joint_inputs, **kwargs
            )
        join_recomputed_effects(
            forward, backward, num_fwd_outputs=kwargs["num_fwd_outputs"]
        )
        regenerated = _regenerated_operators(backward)
        _strip_marks(marked, joint_module, forward, backward)
        record.summary = RetentionSummary(
            memory_bound_flops_per_byte=policy.memory_bound_flops_per_byte,
            regenerated_operators=regenerated,
            unknown_operators=unknown,
        )
        return forward, backward

    return partition


def _mark_retained(
    joint_module: torch.fx.GraphModule, policy: RetentionPolicy
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Mark every compute-bound or unknown forward operator as a value to save.

    Returns the marked nodes' names and the unknown operators. A node that
    already carries a checkpoint policy keeps it: that is the model's own
    say, and this rule fills in only where nothing was said.
    """

    marked: list[str] = []
    unknown: set[str] = set()
    for node in joint_module.graph.nodes:
        if node.op != "call_function":
            continue
        if node.meta.get("partitioner_tag") == "is_backward":
            continue
        if "recompute" in node.meta:
            continue
        operator_class = policy.classify(node)
        if operator_class is OperatorClass.UNKNOWN:
            unknown.add(str(node.target))
        if operator_class in (OperatorClass.COMPUTE_BOUND, OperatorClass.UNKNOWN):
            node.meta["recompute"] = CheckpointPolicy.MUST_SAVE
            marked.append(node.name)
    return tuple(marked), tuple(sorted(unknown))


def _strip_marks(
    marked: Iterable[str],
    *modules: torch.fx.GraphModule,
) -> None:
    """Remove the marks this module made, wherever the partition copied them."""

    names = set(marked)
    if not names:
        return
    for module in modules:
        for node in module.graph.nodes:
            if node.name in names:
                node.meta.pop("recompute", None)


def _regenerated_operators(backward: torch.fx.GraphModule) -> tuple[str, ...]:
    """The forward operators the backward graph computes again."""

    regenerated: set[str] = set()
    for node in backward.graph.nodes:
        if node.op != "call_function":
            continue
        if node.meta.get("partitioner_tag") != "is_forward":
            continue
        target = node.target
        if not isinstance(target, torch._ops.OpOverload) or _is_view(target):
            continue
        regenerated.add(str(target))
    return tuple(sorted(regenerated))


def _classify(node: torch.fx.Node, threshold: float) -> OperatorClass | None:
    target = node.target
    if isinstance(target, torch._ops.HigherOrderOperator):
        return OperatorClass.UNKNOWN
    if not isinstance(target, torch._ops.OpOverload):
        return None
    outputs = _tensors(node.meta.get("val"))
    if not outputs:
        return None
    builtin = _is_builtin(target)
    if target.overloadpacket not in flop_registry:
        return OperatorClass.MEMORY_BOUND if builtin else OperatorClass.UNKNOWN
    try:
        flops = _count_flops(node)
    except Exception as exc:
        raise CaptureError(
            f"the flop formula registered for {target} could not price its traced"
            f" call: {exc}"
        ) from exc
    moved = _bytes(_argument_tensors(node)) + _bytes(outputs)
    if flops <= threshold * max(moved, 1):
        return OperatorClass.MEMORY_BOUND
    return OperatorClass.COMPUTE_BOUND


def _count_flops(node: torch.fx.Node) -> int:
    """Run the operator on its traced values under PyTorch's flop counter.

    The values are fake, so nothing computes; the counter sees the operator
    and asks its formula, as it would for a real call.
    """

    args, kwargs = map_arg((node.args, node.kwargs), lambda item: item.meta["val"])
    with FlopCounterMode(display=False) as counter:
        node.target(*args, **kwargs)  # type: ignore[operator]
    return int(counter.get_total_flops())


def _argument_tensors(node: torch.fx.Node) -> list[torch.Tensor]:
    seen: dict[int, torch.Tensor] = {}
    for argument in tree_flatten((node.args, node.kwargs))[0]:
        if isinstance(argument, torch.fx.Node):
            for tensor in _tensors(argument.meta.get("val")):
                seen.setdefault(id(tensor), tensor)
    return list(seen.values())


def _tensors(value: object) -> list[torch.Tensor]:
    return [item for item in tree_flatten(value)[0] if isinstance(item, torch.Tensor)]


def _bytes(tensors: Iterable[torch.Tensor]) -> int:
    return sum(int(tensor.numel()) * tensor.element_size() for tensor in tensors)


def _is_builtin(target: object) -> bool:
    return isinstance(target, torch._ops.OpOverload) and (
        target.namespace in _BUILTIN_NAMESPACES
    )


def _is_view(target: torch._ops.OpOverload) -> bool:
    return any(argument.alias_info is not None for argument in target._schema.returns)


__all__ = [
    "MEMORY_BOUND_FLOPS_PER_BYTE",
    "OperatorClass",
    "RetentionPolicy",
    "RetentionRecord",
    "RetentionSummary",
    "partition_function",
]
