"""Public PyTorch values and planning entrypoints for ShadowSpill."""

from .api import plan_forward, plan_step
from .callables import PlannedForward, PlannedTrainStep
from .contracts import (
    CaptureError,
    InputGuardError,
    ObjectiveError,
    ObjectiveResult,
    PlanningError,
    TensorSpec,
)
from .diagnostics import (
    DiagnosticsHandle,
    ExecutionTiming,
    PlanAllocationEvent,
    PlanCacheArtifact,
    PlanCompiledOutputView,
    PlanCompiledRoot,
    PlanCompilerProfile,
    PlanDiagnostics,
    PlanGraphPair,
    PlanGraphProfile,
    PlanMutationBinding,
    PlanObjectFootprint,
    PlanOutputView,
    PlanPhaseTiming,
    PlanProfilingMetadata,
    PlanReport,
    PlanStorageRoot,
    PlanTaskStage,
    PlanUniqueStage,
    StepDiagnostics,
    StepResult,
)
from .partition import PartitionPolicy, PartitionSpec
from .runtime_adapter import (
    MemoryPool,
    Runtime,
    RuntimeConfigurationError,
    TransferCapabilities,
    TransferProfile,
)

__all__ = [
    "CaptureError",
    "DiagnosticsHandle",
    "ExecutionTiming",
    "InputGuardError",
    "MemoryPool",
    "ObjectiveError",
    "ObjectiveResult",
    "PartitionPolicy",
    "PartitionSpec",
    "PlanAllocationEvent",
    "PlanCacheArtifact",
    "PlanCompiledOutputView",
    "PlanCompiledRoot",
    "PlanCompilerProfile",
    "PlanDiagnostics",
    "PlanGraphPair",
    "PlanGraphProfile",
    "PlanMutationBinding",
    "PlanObjectFootprint",
    "PlanOutputView",
    "PlanPhaseTiming",
    "PlanProfilingMetadata",
    "PlanReport",
    "PlanStorageRoot",
    "PlanTaskStage",
    "PlanUniqueStage",
    "PlannedForward",
    "PlannedTrainStep",
    "PlanningError",
    "Runtime",
    "RuntimeConfigurationError",
    "StepDiagnostics",
    "StepResult",
    "TensorSpec",
    "TransferCapabilities",
    "TransferProfile",
    "plan_forward",
    "plan_step",
]
