"""Public PyTorch values and planning entrypoints for ShadowSpill."""

from .api import make_step_program, plan_forward, plan_step, pressurefit_program
from .callables import PlannedForward, PlannedTrainStep
from .contracts import (
    AdmissionError,
    CaptureError,
    CompilationError,
    InputGuardError,
    ObjectiveError,
    ObjectiveResult,
    PlanInfeasibleError,
    PlanningError,
    PlanSearchExhaustedError,
    ProfilingError,
    TensorSpec,
)
from .diagnostics import (
    DiagnosticsHandle,
    ExecutionTiming,
    PhaseTimingComparison,
    PlanAllocationEvent,
    PlanCacheArtifact,
    PlanCompiledOutputView,
    PlanCompiledRoot,
    PlanCompilerProfile,
    PlanDiagnostics,
    PlanGraphPair,
    PlanGraphProfile,
    PlanMutationBinding,
    PlanObjectFootprint,
    PlanOutputView,
    PlanPhaseTiming,
    PlanProfilingMetadata,
    PlanReport,
    PlanStorageRoot,
    PlanTaskStage,
    PlanUniqueStage,
    SimulatorTransferComparison,
    StepDiagnostics,
    StepResult,
    StepTimingSummary,
)
from .invocation import InvocationResult
from .partition import PartitionPolicy, PartitionSpec
from .program import (
    AnnotatedProgramPlan,
    MemoryBudgets,
    PressureFitProgram,
    StepProgram,
    TransferBandwidths,
)
from .runtime_adapter import (
    ExecutionTaskIdentity,
    MemoryPool,
    Runtime,
    RuntimeConfigurationError,
    RuntimeExecutionError,
    RuntimeFailureDiagnostics,
    TransferCapabilities,
    TransferProfile,
)
from .sharing import (
    ObjectConsistency,
    SharedInput,
    SharedOutput,
    TensorRef,
    shared_input,
    shared_output,
)
from .state import (
    export_model_state,
    export_optimizer_state,
    import_model_state,
    import_optimizer_state,
    release_model_state,
)

__all__ = [
    "AdmissionError",
    "AnnotatedProgramPlan",
    "CaptureError",
    "CompilationError",
    "DiagnosticsHandle",
    "ExecutionTaskIdentity",
    "ExecutionTiming",
    "InputGuardError",
    "InvocationResult",
    "MemoryBudgets",
    "MemoryPool",
    "ObjectConsistency",
    "ObjectiveError",
    "ObjectiveResult",
    "PartitionPolicy",
    "PartitionSpec",
    "PhaseTimingComparison",
    "PlanAllocationEvent",
    "PlanCacheArtifact",
    "PlanCompiledOutputView",
    "PlanCompiledRoot",
    "PlanCompilerProfile",
    "PlanDiagnostics",
    "PlanGraphPair",
    "PlanGraphProfile",
    "PlanInfeasibleError",
    "PlanMutationBinding",
    "PlanObjectFootprint",
    "PlanOutputView",
    "PlanPhaseTiming",
    "PlanProfilingMetadata",
    "PlanReport",
    "PlanSearchExhaustedError",
    "PlanStorageRoot",
    "PlanTaskStage",
    "PlanUniqueStage",
    "PlannedForward",
    "PlannedTrainStep",
    "PlanningError",
    "PressureFitProgram",
    "ProfilingError",
    "Runtime",
    "RuntimeConfigurationError",
    "RuntimeExecutionError",
    "RuntimeFailureDiagnostics",
    "SharedInput",
    "SharedOutput",
    "SimulatorTransferComparison",
    "StepDiagnostics",
    "StepProgram",
    "StepResult",
    "StepTimingSummary",
    "TensorRef",
    "TensorSpec",
    "TransferBandwidths",
    "TransferCapabilities",
    "TransferProfile",
    "export_model_state",
    "export_optimizer_state",
    "import_model_state",
    "import_optimizer_state",
    "make_step_program",
    "plan_forward",
    "plan_step",
    "pressurefit_program",
    "release_model_state",
    "shared_input",
    "shared_output",
]
