"""Public PyTorch values and planning entrypoints for ShadowSpill."""

from .api import plan_forward, plan_step
from .callables import PlannedForward, PlannedTrainStep
from .contracts import (
    AdmissionError,
    CaptureError,
    CompilationError,
    InputGuardError,
    ObjectiveError,
    ObjectiveResult,
    PlanInfeasibleError,
    PlanningError,
    ProfilingError,
    TensorSpec,
)
from .diagnostics import (
    DiagnosticsHandle,
    ExecutionTiming,
    PhaseTimingComparison,
    PlanAllocationEvent,
    PlanCacheArtifact,
    PlanCompiledOutputView,
    PlanCompiledRoot,
    PlanCompilerProfile,
    PlanDiagnostics,
    PlanGraphPair,
    PlanGraphProfile,
    PlanMutationBinding,
    PlanObjectFootprint,
    PlanOutputView,
    PlanPhaseTiming,
    PlanProfilingMetadata,
    PlanReport,
    PlanStorageRoot,
    PlanTaskStage,
    PlanUniqueStage,
    SimulatorTransferComparison,
    StepDiagnostics,
    StepResult,
    StepTimingSummary,
)
from .partition import PartitionPolicy, PartitionSpec
from .runtime_adapter import (
    ExecutionTaskIdentity,
    MemoryPool,
    Runtime,
    RuntimeConfigurationError,
    RuntimeExecutionError,
    RuntimeFailureDiagnostics,
    TransferCapabilities,
    TransferProfile,
)
from .state import (
    externalize_model_state,
    externalize_optimizer_state,
    relocate_model_state,
    relocate_optimizer_state,
)

__all__ = [
    "AdmissionError",
    "CaptureError",
    "CompilationError",
    "DiagnosticsHandle",
    "ExecutionTaskIdentity",
    "ExecutionTiming",
    "InputGuardError",
    "MemoryPool",
    "ObjectiveError",
    "ObjectiveResult",
    "PartitionPolicy",
    "PartitionSpec",
    "PhaseTimingComparison",
    "PlanAllocationEvent",
    "PlanCacheArtifact",
    "PlanCompiledOutputView",
    "PlanCompiledRoot",
    "PlanCompilerProfile",
    "PlanDiagnostics",
    "PlanGraphPair",
    "PlanGraphProfile",
    "PlanInfeasibleError",
    "PlanMutationBinding",
    "PlanObjectFootprint",
    "PlanOutputView",
    "PlanPhaseTiming",
    "PlanProfilingMetadata",
    "PlanReport",
    "PlanStorageRoot",
    "PlanTaskStage",
    "PlanUniqueStage",
    "PlannedForward",
    "PlannedTrainStep",
    "PlanningError",
    "ProfilingError",
    "Runtime",
    "RuntimeConfigurationError",
    "RuntimeExecutionError",
    "RuntimeFailureDiagnostics",
    "SimulatorTransferComparison",
    "StepDiagnostics",
    "StepResult",
    "StepTimingSummary",
    "TensorSpec",
    "TransferCapabilities",
    "TransferProfile",
    "externalize_model_state",
    "externalize_optimizer_state",
    "plan_forward",
    "plan_step",
    "relocate_model_state",
    "relocate_optimizer_state",
]
