"""Immutable planning and step-execution diagnostics."""

from shadowspill.planner.diagnostics.plan import (
    PlanAllocationABIStep,
    PlanAllocationEvent,
    PlanCacheArtifact,
    PlanCompiledOutputView,
    PlanCompiledRoot,
    PlanCompilerProfile,
    PlanDiagnostics,
    PlanFixedLayoutAttempt,
    PlanGraphPair,
    PlanGraphProfile,
    PlanMutationBinding,
    PlanObjectFootprint,
    PlanOutputView,
    PlanPhaseTiming,
    PlanPhysicalLayout,
    PlanProfilingMetadata,
    PlanReport,
    PlanRepresentativeInput,
    PlanStorageRoot,
    PlanTaskMemoryEnvelope,
    PlanTaskStage,
    PlanUniqueStage,
)

from .execution import (
    AllocatorTrace,
    LaneSummary,
    RuntimeTrace,
    TaskRecord,
    Timelines,
    TransferLane,
    TransferRecord,
    TransferRecords,
)
from .step import (
    DiagnosticsHandle,
    PhaseTimingComparison,
    StepDiagnostics,
    StepResult,
    StepTimingSummary,
)
from .timing import InvocationTiming

__all__ = [
    "AllocatorTrace",
    "DiagnosticsHandle",
    "InvocationTiming",
    "LaneSummary",
    "PhaseTimingComparison",
    "PlanAllocationABIStep",
    "PlanAllocationEvent",
    "PlanCacheArtifact",
    "PlanCompiledOutputView",
    "PlanCompiledRoot",
    "PlanCompilerProfile",
    "PlanDiagnostics",
    "PlanFixedLayoutAttempt",
    "PlanGraphPair",
    "PlanGraphProfile",
    "PlanMutationBinding",
    "PlanObjectFootprint",
    "PlanOutputView",
    "PlanPhaseTiming",
    "PlanPhysicalLayout",
    "PlanProfilingMetadata",
    "PlanReport",
    "PlanRepresentativeInput",
    "PlanStorageRoot",
    "PlanTaskMemoryEnvelope",
    "PlanTaskStage",
    "PlanUniqueStage",
    "RuntimeTrace",
    "StepDiagnostics",
    "StepResult",
    "StepTimingSummary",
    "TaskRecord",
    "Timelines",
    "TransferLane",
    "TransferRecord",
    "TransferRecords",
]
